### ISSUE TITLE
M République -> M Père-Lachaise

### ISSUE THREAD

**Issue by yaaax** [joachimesque/paris-a-velo#4]
M République -> M Père-Lachaise : 9mn
M Père-Lachaise -> M République : 7mn

(j'ai pris large hein ;)

**Comment by joachimesque** [comment]
Merci ! c'est un axe que j'avais oublié (et j'en ai profité pour brancher les points différemment en ajoutant Voltaire), je trouve que 7 minutes c'est un peu long, généralement je mets une dizaine de minutes dans toute la descente entre Gambetta et République, donc j'ai baissé tes temps d'1 minute
